global class AM_Actualizar_Estado_Facturas_Sched{// implements Schedulable {
  //RM 14-01-2019. Commented. Not in use 
  /*
  global void execute(SchedulableContext sc) {
    AM_Actualizar_Estado_Facturas_Batch b = new AM_Actualizar_Estado_Facturas_Batch();
    database.executebatch(b,2);

    //System.schedule('Hourly run - Actualizacion Facturas', '0 0 * * * ?', new AM_Actualizar_Estado_Facturas_Sched());
  }*/
}